title: Morphy Kuffour's Blog
email: morpkuff@protonmail.com
description: >- 
  nixos, security, qmk, vim, neovim, scripting, keyboards, 
# baseurl: "" # the subpath of your site, e.g. /blog
domain: morphykuffour.github.io
url: https://morphykuffour.github.io 
bluesky: morphk
github_username: morphykuffour

minima:
  skin: dark
  date_format: "%b %-d, %Y"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      comments: true
